"""Write LaTeX macros with every number quoted in the text, straight from the result summaries
(scripts/analyze.py), so that the abstract, the text and the tables can never disagree.

usage: python scripts/make_numbers.py [path/to/numbers.tex]
"""
import json
import os
import sys

import numpy as np

ROOT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "results")
OUT = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(ROOT), "paper", "numbers.tex")
lines = ["% Auto-generated by scripts/make_numbers.py -- do not edit by hand."]
f3 = lambda x: f"{x:.3f}"  # noqa: E731
f1 = lambda x: f"{x:.1f}"  # noqa: E731


def m(name, val):
    lines.append(f"\\newcommand{{\\{name}}}{{{val}}}")


def load(ds):
    p = os.path.join(ROOT, ds, "summary.json")
    return json.load(open(p)) if os.path.exists(p) else None


def plural(unit, xs):
    xs = [str(x) for x in xs]
    if len(xs) == 1:
        return f"{unit}~{xs[0]}"
    return f"{unit}s~" + ", ".join(xs[:-1]) + f" and~{xs[-1]}"


def join_and(parts):
    if len(parts) <= 1:
        return "".join(parts)
    return ", ".join(parts[:-1]) + " and " + parts[-1]


def holm(pvals):
    p = np.asarray(pvals, float); n = len(p)
    order = np.argsort(p); adj = np.empty(n); run = 0.0
    for k, i in enumerate(order):
        run = max(run, min(1.0, (n - k) * p[i])); adj[i] = run
    return adj.tolist()


def rec_mean(src, mode, H, metric="NDCG@10"):
    return float(np.mean([src[str(h)][mode][metric][0] for h in range(H)]))


def rec_macros(S, H, suffix):
    rk, rb = S.get("opal_rank"), S.get("rec_baselines", {})
    if not rk or not rb:
        return
    best = {}
    for mode in ("all", "new"):
        cand = {n: rec_mean(v, mode, H) for n, v in rb.items() if all(str(h) in v and mode in v[str(h)] for h in range(H))}
        bname = max(cand, key=cand.get)
        o = rec_mean(rk, mode, H)
        best[mode] = (bname, cand[bname], o)
        m(f"ndcgOpal{mode.capitalize()}{suffix}", f3(o))
        m(f"ndcgBest{mode.capitalize()}{suffix}", f3(cand[bname]))
        m(f"bestRec{mode.capitalize()}{suffix}", bname)
        m(f"ndcgGain{mode.capitalize()}{suffix}", f1(100 * (o / cand[bname] - 1)))
    # paired Wilcoxon tests of per-learner NDCG@10 against the strongest recommender, Holm-adjusted over horizons
    unit = "week" if suffix == "" else "day"
    hnum = {"": [2, 4, 6, 8, 12], "Mooc": [1, 3, 5, 7]}[suffix]
    wil = S.get("wilcoxon", {})
    for mode in ("all", "new"):
        b = best[mode][0]
        if b not in wil:
            continue
        hs = [str(h) for h in range(H) if str(h) in wil[b] and mode in wil[b][str(h)]]
        ps = holm([wil[b][h][mode]["p"] for h in hs])
        better = [hnum[int(h)] for h, p in zip(hs, ps) if p < 0.05 and wil[b][h][mode]["opal"] > wil[b][h][mode]["base"]]
        worse = [hnum[int(h)] for h, p in zip(hs, ps) if p < 0.05 and wil[b][h][mode]["opal"] < wil[b][h][mode]["base"]]
        same = [hnum[int(h)] for h, p in zip(hs, ps) if p >= 0.05]
        parts = []
        if better:
            parts.append(f"significantly higher at {plural(unit, better)}")
        if worse:
            parts.append(f"significantly lower at {plural(unit, worse)}")
        if same:
            parts.append(f"not significantly different at {plural(unit, same)}")
        m(f"wil{mode.capitalize()}Sentence{suffix}", join_and(parts))
    for mode in ("all", "new"):
        b = best[mode][0]
        src = rb[b]
        m(f"recallOpal{mode.capitalize()}{suffix}", f3(rec_mean(rk, mode, H, "Recall@10")))
        m(f"recallBest{mode.capitalize()}{suffix}", f3(rec_mean(src, mode, H, "Recall@10")))
        m(f"ndcgDiff{mode.capitalize()}{suffix}", f"{100 * (rec_mean(rk, mode, H) - rec_mean(src, mode, H)):.1f}")
    hr = [rec_mean(rk, "all", H, "HR@10")] + [rec_mean(v, "all", H, "HR@10") for n, v in rb.items()
                                               if n in ("SASRec", "GRU4Rec", "RecentPop", "Repeat", "Pop")]
    m(f"hrAllMin{suffix}", f"{np.floor(min(hr) * 100) / 100:.2f}")
    RS = {"Pop": "Pop", "RecentPop": "RecentPop", "Repeat": "Repeat", "ItemKNN": "ItemKnn", "BPR-MF": "BprMf",
          "LightGCN": "LightGcn", "GRU4Rec": "GruRec", "SASRec": "SasRec"}
    for n, sh in RS.items():
        if n in rb:
            for mode in ("all", "new"):
                v = rec_mean(rb[n], mode, H)
                m(f"ndcg{mode.capitalize()}{sh}{suffix}", f3(v))
    fl = S.get("flagged_rec", {})
    vals = [fl[str(h)] for h in range(H) if str(h) in fl and "OPAL" in fl[str(h)] and fl[str(h)]["OPAL"]["flagged"] is not None]
    if vals:
        m(f"ndcgFlagOpal{suffix}", f3(np.mean([v["OPAL"]["flagged"] for v in vals])))
        m(f"ndcgOthersOpal{suffix}", f3(np.mean([v["OPAL"]["others"] for v in vals])))
        for b in ("SASRec", "RecentPop"):
            bv = [v[b]["flagged"] for v in vals if b in v and v[b]["flagged"] is not None]
            if bv:
                m(f"ndcgFlag{b}{suffix}", f3(np.mean(bv)))
                m(f"ndcgOthers{b}{suffix}", f3(np.mean([v[b]["others"] for v in vals if b in v and v[b]["others"] is not None])))


SHORT = {"LightGBM": "Lgbm", "XGBoost": "Xgb", "RF": "Rf", "HGB+Platt": "Hgb", "MLP": "Mlp", "LR": "Lr", "GRU": "Gru",
         "Transformer": "Trf", "R-GCN": "Rgcn", "HGT": "Hgt", "opal": "Opal"}


def signed(x, d=2):
    if round(abs(x), d) == 0:
        return f"{0:.{d}f}"
    return ("$+$" if x > 0 else "$-$") + f"{abs(x):.{d}f}"


def pfmt(p):
    return "$p<0.001$" if p < 1e-3 else f"$p={p:.3f}$"


def risk_macros(S, H, suffix, words, words_num=None):
    """Per-seed means (as in the tables) are the headline numbers; seed-ensemble AUCs and the DeLong /
    bootstrap comparisons of the ensembles get their own macros."""
    R, ens = S["risk"], S["ensemble_auc"]
    for n, sh in SHORT.items():
        if n not in R:
            continue
        m(f"aucMean{sh}{suffix}", f3(R[n]["mean_AUC"][0]))
        m(f"aucSd{sh}{suffix}", f3(R[n]["mean_AUC"][1]))
        for i, w in enumerate(words):
            m(f"auc{sh}W{w}{suffix}", f3(R[n][str(i)]["AUC"][0]))
        if n in ens:
            m(f"aucEns{sh}{suffix}", f3(np.mean([ens[n][str(i)] for i in range(H)])))
            for i, w in enumerate(words):
                m(f"aucEns{sh}W{w}{suffix}", f3(ens[n][str(i)]))
    mo = R["opal"]["mean_AUC"][0]
    m(f"aucOpalMean{suffix}", f3(mo))
    base = {n: R[n]["mean_AUC"][0] for n in R if n in SHORT and n != "opal"}
    bn = max(base, key=base.get)
    m(f"aucBestBaseMean{suffix}", f3(base[bn])); m(f"bestRiskBase{suffix}", bn.replace("HGB+Platt", "HGB + Platt"))
    m(f"aucGapBest{suffix}", f1(100 * (base[bn] - mo)))
    if "LightGBM" in R:
        ml = R["LightGBM"]["mean_AUC"][0]
        m(f"aucLgbmMean{suffix}", f3(ml)); m(f"aucGapLgbm{suffix}", f1(100 * (ml - mo)))
        m(f"aucLgbmWlast{suffix}", f3(R["LightGBM"][str(H - 1)]["AUC"][0]))
    eo = np.mean([ens["opal"][str(i)] for i in range(H)])
    m(f"ensGainOpal{suffix}", f1(100 * (eo - mo)))
    # OPAL minus baseline for the seed ensembles: difference, 95% bootstrap CI and Holm-adjusted DeLong p
    for n, st in S.get("stats_vs_opal", {}).items():
        sh = SHORT.get(n)
        if sh is None:
            continue
        for i, w in enumerate(words):
            b = st[str(i)]["boot"]
            m(f"d{sh}W{w}{suffix}", signed(100 * b["diff"]))
            m(f"ci{sh}W{w}{suffix}", f"[{signed(100 * b['ci_low'])}, {signed(100 * b['ci_high'])}]")
            m(f"p{sh}W{w}{suffix}", pfmt(st[str(i)]["p_holm"]))
    # spread of the mean AUC over all risk models, and over the neural sequence and static graph baselines
    allm = {n: R[n]["mean_AUC"][0] for n in SHORT if n in R}
    lo, hi = min(allm, key=allm.get), max(allm, key=allm.get)
    lab = lambda n: {"opal": "OPAL", "HGB+Platt": "HGB + Platt", "LR": "logistic regression", "RF": "random forest"}.get(n, n)  # noqa: E731
    m(f"aucRangeLow{suffix}", f3(allm[lo])); m(f"aucRangeLowModel{suffix}", lab(lo))
    m(f"aucRangeHigh{suffix}", f3(allm[hi])); m(f"aucRangeHighModel{suffix}", lab(hi))
    m(f"aucRangeSpread{suffix}", f1(100 * (allm[hi] - allm[lo])))
    neur = {n: allm[n] for n in ("GRU", "Transformer", "R-GCN", "HGT") if n in allm}
    if neur:
        m(f"aucNeuralLow{suffix}", f3(min(neur.values()))); m(f"aucNeuralHigh{suffix}", f3(max(neur.values())))
    trees = {n: allm[n] for n in ("RF", "XGBoost", "LightGBM", "HGB+Platt") if n in allm}
    if trees:
        m(f"aucTreeLow{suffix}", f3(min(trees.values()))); m(f"aucTreeHigh{suffix}", f3(max(trees.values())))
    # OPAL vs the four tree ensembles at the middle decision points (all but the first two and the last)
    trees = [n for n in ("RF", "XGBoost", "LightGBM", "HGB+Platt") if n in S.get("stats_vs_opal", {})]
    mid = list(range(2, H - 1))
    if trees and mid:
        st = S["stats_vs_opal"]
        cmp = [(n, i, st[n][str(i)]) for n in trees for i in mid]
        m(f"maxAbsMid{suffix}", f"{max(abs(c['boot']['diff']) for _, _, c in cmp) * 100:.2f}")
        sig = [(n, i, c) for n, i, c in cmp if c["p_holm"] < 0.05]
        num = ["none", "one", "two", "three", "four", "five", "six", "seven", "eight"]
        if not sig:
            txt = f"none of these {num[len(cmp)]} comparisons was significant"
        else:
            unit = "week" if suffix == "" else "day"
            det = "; ".join(f"{n.replace('HGB+Platt', 'HGB + Platt')} at {unit}~{words_num[i]}, {pfmt(c['p_holm'])}" for n, i, c in sig)
            txt = f"{num[len(sig)]} of these {num[len(cmp)]} comparisons {'was' if len(sig) == 1 else 'were'} significant ({det})"
        m(f"sigMidSentence{suffix}", txt)
    # one sentence per baseline: at which decision points the seed ensembles differ significantly
    unit_ = "week" if suffix == "" else "day"
    for n, st in S.get("stats_vs_opal", {}).items():
        sh = SHORT.get(n)
        if sh is None:
            continue
        ob = [words_num[i] for i in range(H) if st[str(i)]["p_holm"] < 0.05 and st[str(i)]["boot"]["diff"] > 0]
        bb = [words_num[i] for i in range(H) if st[str(i)]["p_holm"] < 0.05 and st[str(i)]["boot"]["diff"] < 0]
        if not ob and not bb:
            txt = "no difference was significant"
        else:
            parts = ([f"OPAL was significantly better at {plural(unit_, ob)}"] if ob else []) + \
                    ([f"the baseline was significantly better at {plural(unit_, bb)}"] if bb else [])
            txt = join_and(parts)
        m(f"cmp{sh}{suffix}", txt)
        m(f"maxAbsDiff{sh}{suffix}", f"{max(abs(st[str(i)]['boot']['diff']) for i in range(H)) * 100:.2f}")
    # joint sentence for the two static graph networks
    gs = S.get("stats_vs_opal", {})
    if "R-GCN" in gs and "HGT" in gs:
        none = lambda st: all(st[str(i)]["p_holm"] >= 0.05 for i in range(H))  # noqa: E731
        if none(gs["R-GCN"]) and none(gs["HGT"]):
            m(f"cmpGraphSentence{suffix}", "No difference between the seed ensembles of OPAL and those of R-GCN or HGT was significant.")
        else:
            m(f"cmpGraphSentence{suffix}", f"Compared with R-GCN, \\cmpRgcn{suffix}{{}}; compared with HGT, \\cmpHgt{suffix}{{}}.")
    if "LightGBM" in S.get("stats_vs_opal", {}):
        p = S["stats_vs_opal"]["LightGBM"][str(H - 1)]["p_holm"]
        m(f"pLgbmWlast{suffix}", f"{p:.4f}" if p >= 1e-4 else "<0.0001")
    for k, nm in (("PR_AUC", "prauc"), ("F1", "fone"), ("MCC", "mcc"), ("Brier", "brier"), ("ECE", "ece")):
        for n, sh in SHORT.items():
            if n in R:
                m(f"{nm}{sh}{suffix}", f3(R[n][f"mean_{k}"][0]))
    m(f"eceOpalMean{suffix}", f3(R["opal"]["mean_ECE"][0]))
    m(f"eceRawOpalMean{suffix}", f3(R["opal"]["mean_ECE_raw"][0]))
    m(f"opalParams{suffix}", f"{R['opal']['n_params']:,}")
    m(f"opalTrainMin{suffix}", f1(R["opal"]["train_sec"] / 60))
    m(f"opalInferSec{suffix}", f1(R["opal"]["infer_sec"]))
    m(f"nSeedsOpal{suffix}", ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten"][R["opal"]["n_seeds"]])


DS = os.path.join(ROOT, "dataset_stats.json")
if os.path.exists(DS):
    st_ = json.load(open(DS))["oulad"]
    m("nTestCohorts", str(st_["test"]["n_cohorts"]))
    m("nFitsStack", str(5 + 5 * st_["test"]["n_cohorts"]))
    m("posRateVal", f1(100 * st_["val"]["pos_rate"])); m("posRateTest", f1(100 * st_["test"]["pos_rate"]))
def fairness_macros(S, H=5):
    fa = S.get("fairness", {})
    AT = {"gender": "Gender", "age_band": "Age", "imd_band": "Imd", "disability": "Dis"}
    for n, sh in (("opal", "Opal"), ("LightGBM", "Lgbm"), ("GRU", "Gru"), ("XGBoost", "Xgb"), ("HGB+Platt", "Hgb")):
        if n not in fa:
            continue
        for a, al in AT.items():
            g = [fa[n][str(h)]["gaps"][a] for h in range(H)]
            m(f"dTpr{sh}{al}", f3(np.mean([x["dTPR"] for x in g])))
            m(f"dFpr{sh}{al}", f3(np.mean([x["dFPR"] for x in g])))
            m(f"abroca{sh}{al}", f3(np.mean([fa[n][str(h)]["abroca"][a] for h in range(H)])))
        gr = lambda a, grp, k: np.mean([fa[n][str(h)]["gaps"][a]["groups"][grp][k] for h in range(H)])  # noqa: E731
        m(f"fprFemale{sh}", f3(gr("gender", "F", "FPR"))); m(f"fprMale{sh}", f3(gr("gender", "M", "FPR")))
        m(f"tprImdUnknown{sh}", f3(gr("imd_band", "unknown", "TPR")))
        m(f"tprImdLow{sh}", f3(gr("imd_band", "low (0-50%)", "TPR")))
        m(f"tprAgeOld{sh}", f3(gr("age_band", "35+", "TPR"))); m(f"tprAgeYoung{sh}", f3(gr("age_band", "0-35", "TPR")))
    if "opal" in fa:
        m("nImdUnknown", str(int(np.mean([fa["opal"][str(h)]["gaps"]["imd_band"]["groups"]["unknown"]["n"] for h in range(H)]))))
    ab = [np.mean([fa[n][str(h)]["abroca"]["gender"] for h in range(H)]) for n in fa]
    if ab:
        m("abrocaGenderLow", f3(min(ab))); m("abrocaGenderHigh", f3(max(ab)))


def efficiency_macros(S, ds, suffix):
    """Training/inference cost.  The controlled benchmark (scripts/benchmark_efficiency.py, idle machine, one
    thread) is used when available; otherwise the times logged by the main runs, which shared the CPU."""
    import glob
    eff = {}
    p = os.path.join(ROOT, "efficiency.json")
    if os.path.exists(p):
        eff = json.load(open(p)).get(ds, {})
    m(f"effControlled{suffix}", "yes" if eff else "no")
    diffs = [e["max_abs_logit_diff_vs_main_run"] for e in eff.values() if e.get("max_abs_logit_diff_vs_main_run") is not None]
    if diffs:
        m(f"effMaxDiff{suffix}", f"{max(diffs):.1e}" if max(diffs) > 0 else "0")
        m(f"effNReproduced{suffix}", str(len(diffs)))
    R = S["risk"]
    for n, sh in (("opal", "Opal"), ("GRU", "Gru"), ("Transformer", "Trf"), ("R-GCN", "Rgcn"), ("HGT", "Hgt"),
                  ("LightGBM", "Lgbm"), ("XGBoost", "Xgb")):
        e = eff.get(n)
        if e:
            tr, inf, par = e["train_sec"], e.get("infer_sec"), e.get("n_params")
        elif n in R:
            tr, inf, par = R[n]["train_sec"], R[n]["infer_sec"], R[n]["n_params"]
        else:
            continue
        m(f"trainMin{sh}{suffix}", f1(tr / 60))
        if inf is not None:
            m(f"inferSec{sh}{suffix}", f1(inf))
        if par:
            m(f"params{sh}{suffix}", f"{int(par):,}")
    for n, sh in (("SASRec", "SasRec"), ("GRU4Rec", "GruRec")):
        e = eff.get(n)
        if e:
            m(f"fitMin{sh}{suffix}", f1(e["train_sec"] / 60)); m(f"nFits{sh}{suffix}", str(e["fits"]))
        else:
            fs = sorted(glob.glob(os.path.join(ROOT, ds, "rec", f"{n}_seed*.json")))
            if fs:
                m(f"fitMin{sh}{suffix}", f1(np.mean([json.load(open(x))["_sec"] for x in fs]) / 60))


VH = os.path.join(ROOT, "val_variant_hybrid.json")
if os.path.exists(VH):
    vh = json.load(open(VH))
    for ds, sfx in (("oulad", "Oulad"), ("act-mooc", "Mooc")):
        if ds in vh:
            m(f"hybVal{sfx}", f3(vh[ds]["hybrid_seed0"][2])); m(f"baseVal{sfx}Mean", f3(vh[ds]["base_mean"][2]))
            m(f"baseVal{sfx}Sd", f3(vh[ds]["base_sd"][2]))
So = load("oulad")
if So and "opal" in So["risk"]:
    risk_macros(So, 5, "", ["two", "four", "six", "eight", "twelve"], [2, 4, 6, 8, 12])
    # ablation study (seeds 0-2 of the full model as reference)
    AB = {"abl_no_graph": "NoGraph", "abl_no_coevo": "NoCoevo", "abl_no_rec": "NoRec", "abl_no_peer": "NoPeer",
          "abl_no_featpath": "NoFeat", "abl_no_assess": "NoAssess"}
    af = So.get("ablation_full")
    if af:
        fa = af["risk"]["mean_AUC"][0]
        fr = af.get("rank", {})
        m("ablFullAuc", f3(fa))
        for key, sh in AB.items():
            a = So.get("ablation", {}).get(key)
            if not a:
                continue
            m(f"ablAuc{sh}", f3(a["mean_AUC"][0])); m(f"ablDauc{sh}", signed(100 * (a["mean_AUC"][0] - fa)))
            m(f"ablAbsDauc{sh}", f"{abs(100 * (a['mean_AUC'][0] - fa)):.2f}")
            dl = a.get("delong_vs_full", {})
            diffs = [100 * (v["auc1"] - v["auc2"]) for v in dl.values()]
            sig = [100 * (v["auc1"] - v["auc2"]) for v in dl.values() if v["p_holm"] < 0.05]
            m(f"ablNsig{sh}", ["no", "one", "two", "three", "four", "five"][len(sig)])
            if diffs:
                m(f"ablEnsMin{sh}", signed(min(diffs))); m(f"ablEnsMax{sh}", signed(max(diffs)))
            rk = So.get("ablation_rank", {}).get(key)
            if rk and fr:
                for mode in ("all", "new"):
                    dv = np.mean([rk[str(h)][mode]["NDCG@10"][0] - fr[str(h)][mode]["NDCG@10"][0] for h in range(5)])
                    m(f"ablDndcg{mode.capitalize()}{sh}", signed(100 * dv))
                    m(f"ablAbsDndcg{mode.capitalize()}{sh}", f"{abs(100 * dv):.2f}")
    vs = os.path.join(ROOT, "oulad", "ablation_val_scores.json")
    if os.path.exists(vs):
        v = json.load(open(vs))
        for key, sh in (("opal", "Full"), ("abl_no_featpath", "NoFeat"), ("abl_no_peer", "NoPeer")):
            if key in v:
                m(f"ablVal{sh}", f3(np.mean(v[key])))
        m("ablValSdFull", f3(np.std(v["opal"])))
    rec_macros(So, 5, "")
    fairness_macros(So)
    efficiency_macros(So, "oulad", "")
    pp = os.path.join(ROOT, "oulad", "protocol_inflation.json")
    pr = json.load(open(pp)) if os.path.exists(pp) else So.get("protocol")
    if pr:
        W = ["two", "four", "six", "eight", "twelve"]
        gain = [r - t for r, t in zip(pr["random"], pr["temporal"])]
        m("randomInflationMin", f1(100 * min(gain))); m("randomInflationMax", f1(100 * max(gain)))
        m("aucLeaky", f"{pr['leaky_temporal']:.2f}")
        m("aucLeakyPrecise", f3(pr["leaky_temporal"]))
        for key, nm in (("temporal", "Temp"), ("random", "Rand"), ("random_same_size", "Same"), ("within_presentation", "Within")):
            if pr.get(key):
                for i, w in enumerate(W):
                    m(f"prot{nm}W{w}", f3(pr[key][i]))
                m(f"prot{nm}Mean", f3(np.mean(pr[key])))
                if key != "temporal":
                    g = [a - t for a, t in zip(pr[key], pr["temporal"])]
                    m(f"prot{nm}GainMin", f1(100 * min(g))); m(f"prot{nm}GainMax", f1(100 * max(g)))
                    m(f"prot{nm}GainMean", f1(100 * np.mean(g)))
        if pr.get("random_same_size"):
            share = np.mean([a - t for a, t in zip(pr["random_same_size"], pr["temporal"])]) / np.mean(gain)
            m("protSameShare", f"{100 * share:.0f}")
    # marking-delay sensitivity: tutor-marked scores known 14 days after submission
    import glob
    # Marking-delay sensitivity (assessment scores delayed by 14 days).  The per-seed AUCs are computed from the
    # stored predictions when they are present and cached in results/oulad/lag14_summary.json, so that the
    # macros can also be regenerated from the summaries alone.
    import pickle
    from sklearn.metrics import roc_auc_score
    lag_path = os.path.join(ROOT, "oulad", "lag14_summary.json")
    lag = json.load(open(lag_path)) if os.path.exists(lag_path) else {}
    for n, sh in (("LightGBM", "Lgbm"), ("opal", "Opal")):
        fs = sorted(glob.glob(os.path.join(ROOT, "oulad_lag14", n, "seed*.pkl")))
        if fs:
            per, base_per = [], []
            for fp in fs:
                r = pickle.load(open(fp, "rb"))
                per.append([roc_auc_score(r["test"][h]["y"], r["test"][h]["logit"]) for h in range(5)])
                del r
                r = pickle.load(open(os.path.join(ROOT, "oulad", n, os.path.basename(fp)), "rb"))  # same seeds, main runs
                base_per.append([roc_auc_score(r["test"][h]["y"], r["test"][h]["logit"]) for h in range(5)])
                del r
            lag[n] = {"seeds": [os.path.basename(f)[4:-4] for f in fs], "auc_lag14": per, "auc_main": base_per}
            json.dump(lag, open(lag_path, "w"), indent=1)
        if n not in lag:
            continue
        per, base_per = lag[n]["auc_lag14"], lag[n]["auc_main"]
        mean_lag, base = float(np.mean(per)), float(np.mean(base_per))
        m(f"aucLag{sh}", f3(mean_lag)); m(f"nSeedsLag{sh}", str(len(per)))
        m(f"aucLagDiff{sh}", signed(100 * (mean_lag - base)))
        m(f"aucLag{sh}Wtwelve", f3(float(np.mean([p[4] for p in per]))))
Sm = load("act-mooc")
if Sm and "opal" in Sm["risk"]:
    risk_macros(Sm, 4, "Mooc", ["one", "three", "five", "seven"], [1, 3, 5, 7])
    rec_macros(Sm, 4, "Mooc")
    efficiency_macros(Sm, "act-mooc", "Mooc")
# every macro used in the manuscript must exist; results that are not available yet are marked
REQUIRED = ["aucOpalWtwo", "aucOpalWtwelve", "aucLgbmWlast", "aucOpalMean", "aucLgbmMean", "aucGapLgbm", "eceOpalMean", "opalParams",
            "ndcgGainAll", "ndcgGainNew", "bestRecAll", "randomInflationMin", "randomInflationMax", "aucLeaky",
            "aucLagLgbm", "aucLagOpal", "aucLagDiffLgbm", "aucLagDiffOpal", "nSeedsLagOpal"]
defined = {l.split("{")[1].split("}")[0].lstrip("\\") for l in lines if l.startswith("\\newcommand")}
for r in REQUIRED:
    if r not in defined:
        m(r, "\\textbf{[pending]}")
open(OUT, "w").write("\n".join(lines) + "\n")
print("\n".join(lines))
